// <auto-generated />
using System;
using CarbonReport.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(CarbonDbContext))]
    [Migration("20260529093431_InitialCredentials")]
    partial class InitialCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Domain.Entities.EmissionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CO2Factor")
                        .HasPrecision(18, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmissionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CO2Factor = 0.41999999999999998,
                            Name = "Stromnetz (Standard)",
                            Scope = 2,
                            Unit = "kWh"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CO2Factor = 0.35999999999999999,
                            Name = "Stromnetz (Ökostrom)",
                            Scope = 2,
                            Unit = "kWh"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-222222222222"),
                            CO2Factor = 2.6400000000000001,
                            Name = "Fuhrpark (Diesel)",
                            Scope = 1,
                            Unit = "Liters"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CO2Factor = 2.5,
                            Name = "Fuhrpark (Benzin)",
                            Scope = 1,
                            Unit = "Liters"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-444444444444"),
                            CO2Factor = 0.20000000000000001,
                            Name = "Heizung (Erdgas)",
                            Scope = 1,
                            Unit = "kWh"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmissionCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmissionCategoryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("EmissionRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000001"),
                            ConsumptionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strom Jan",
                            EmissionCategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 4200.0
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000001"),
                            ConsumptionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diesel Jan",
                            EmissionCategoryId = new Guid("22222222-1111-1111-1111-222222222222"),
                            Quantity = 1100.0
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000001"),
                            ConsumptionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Erdgas Jan",
                            EmissionCategoryId = new Guid("44444444-1111-1111-1111-444444444444"),
                            Quantity = 8500.0
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000002"),
                            ConsumptionDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strom Feb",
                            EmissionCategoryId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Quantity = 3900.0
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000002"),
                            ConsumptionDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diesel Feb",
                            EmissionCategoryId = new Guid("22222222-1111-1111-1111-222222222222"),
                            Quantity = 950.0
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000002"),
                            ConsumptionDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Erdgas Feb",
                            EmissionCategoryId = new Guid("44444444-1111-1111-1111-444444444444"),
                            Quantity = 7800.0
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000003"),
                            ConsumptionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strom Mär",
                            EmissionCategoryId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Quantity = 4500.0
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000003"),
                            ConsumptionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diesel Mär",
                            EmissionCategoryId = new Guid("22222222-1111-1111-1111-222222222222"),
                            Quantity = 1300.0
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000003"),
                            ConsumptionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Erdgas Mär",
                            EmissionCategoryId = new Guid("44444444-1111-1111-1111-444444444444"),
                            Quantity = 6200.0
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000004"),
                            ConsumptionDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strom Apr",
                            EmissionCategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 3100.0
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000004"),
                            ConsumptionDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diesel Apr",
                            EmissionCategoryId = new Guid("22222222-1111-1111-1111-222222222222"),
                            Quantity = 1200.0
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000004"),
                            ConsumptionDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Erdgas Apr",
                            EmissionCategoryId = new Guid("44444444-1111-1111-1111-444444444444"),
                            Quantity = 3100.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = new Guid("33333333-1111-1111-1111-333333333333"),
                            LicensePlate = "WOB-P 123",
                            Name = "VW Golf GTE",
                            Type = 2
                        },
                        new
                        {
                            VehicleId = new Guid("33333333-2222-2222-2222-333333333333"),
                            LicensePlate = "WOB-E 999",
                            Name = "Tesla Model 3",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmissionRecord", b =>
                {
                    b.HasOne("Domain.Entities.EmissionCategory", "Category")
                        .WithMany("Records")
                        .HasForeignKey("EmissionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Records")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Category");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.EmissionCategory", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
