// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(CarbonDbContext))]
    partial class CarbonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Domain.Entities.EmissionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CO2Factor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmissionCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            CO2Factor = 0.38,
                            Name = "Stromnetz Deutschland",
                            Scope = 2,
                            Unit = "kWh"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmissionFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmissionCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Factor")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmissionCategoryId");

                    b.ToTable("EmissionFactors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            EmissionCategoryId = new Guid("4fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Factor = 0.38500000000000001,
                            Source = "Umweltbundesamt",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilityId = new Guid("85a21e42-7db2-4a1e-84b2-e1c9d2f34e01"),
                            Country = "Deutschland",
                            FacilityName = "Werk München"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EmissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CalculatedCO2e")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmissionCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmissionCategoryId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("VehicleId");

                    b.ToTable("EmissionRecords");
                });

            modelBuilder.Entity("Domain.Entities.EmissionFactor", b =>
                {
                    b.HasOne("Domain.Entities.EmissionCategory", "Category")
                        .WithMany("HistoricalFactors")
                        .HasForeignKey("EmissionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EmissionRecord", b =>
                {
                    b.HasOne("Domain.Entities.EmissionCategory", "Category")
                        .WithMany("EmissionRecords")
                        .HasForeignKey("EmissionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Facility", "Facility")
                        .WithMany("EmissionRecords")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("EmissionRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Facility");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.EmissionCategory", b =>
                {
                    b.Navigation("EmissionRecords");

                    b.Navigation("HistoricalFactors");
                });

            modelBuilder.Entity("Domain.Entities.Facility", b =>
                {
                    b.Navigation("EmissionRecords");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("EmissionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
